[package]
name = "rocas"
version = "1.0.1"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
log = "0.4.29"
env_logger = "0.11.9"

[dependencies.watcher]
version = "0.1.0"
path = "../watcher"

[dependencies.forgeconf]
version = "0.4.1"
features = ["toml", "miette"]
default-features = false
